services:
  backend:
    image: alejoide/learn-time-web:latest
    build:
      context: ..
      dockerfile: Dockerfile
      build_args:
        - API_URL=http://localhost:80
    container_name: learn-time-backend
    volumes:
      - static:/app/src/.web/_static

  frontend:
    image: nginx:latest
    container_name: learn-time-frontend
    ports:
      - 80:80
    volumes:
      - static:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  static:
    name: learn-time-static
