services:
  backend:
    image: alejoide/learn-time-web:latest
    container_name: learn-time-backend
    restart: unless-stopped
    volumes:
      - static:/app/src/.web/_static
    networks:
      - default

  frontend:
    image: nginx:latest
    container_name: learn-time-frontend
    restart: unless-stopped
    volumes:
      - static:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - nginx-proxy
      - default

volumes:
  static:
    name: learn-time-static

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
