name: build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build and push
    runs-on: self-hosted
    environment: prod
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
          images: |
            alejoide/my-links-web
      -
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./src
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          build-args: |
            API_URL=${{ secrets.API_URL }}

